# Generated by Django 5.0.4 on 2024-05-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinemabooking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='planebooking',
            name='flight_number',
        ),
        migrations.RemoveField(
            model_name='planebooking',
            name='user',
        ),
        migrations.AddField(
            model_name='planebooking',
            name='plane_number',
            field=models.CharField(default='DEFAULT_PLANE_NUMBER', max_length=100),
        ),
        migrations.AddField(
            model_name='planebooking',
            name='seats_available',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BusBooking',
        ),
        migrations.DeleteModel(
            name='CinemaBooking',
        ),
    ]
