# Generated by Django 5.0.4 on 2024-05-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_plane_delete_planebooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busnumber', models.CharField(max_length=10)),
                ('busname', models.CharField(max_length=100)),
                ('departureplace', models.CharField(max_length=100)),
                ('arrivalplace', models.CharField(max_length=100)),
                ('departuretime', models.TimeField()),
                ('date', models.DateField()),
                ('seatsavailable', models.IntegerField()),
                ('priceperseat', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
